name: Build docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  IMAGE_NAME: "ghcr.io/kitmatheinfo/latexfogel"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23
      - uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@786422608c7bded2bbc9741ad9f91356842bf520 # v14
        with:
          fail-mode: false
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6.2.0
        with:
          images: "${{ env.IMAGE_NAME }}"
          sep-tags: ","
          sep-labels: ","
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=edge,branch=master
            type=sha
            type=sha,format=long

      - name: Login to registry
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build
        if: github.event_name == 'pull_request'
        run: nix build .#docker

      - name: Build and publish docker image
        if: github.event_name != 'pull_request'
        run: nix develop .#docker --ignore-environment --keep PATH --keep IMAGE_NAME --command publish "${{ steps.meta.outputs.tags }}"
        env:
          IMAGE_NAME: "${{ env.IMAGE_NAME }}"
